event-driven-io/Pongo

README.md

Tiny fix in the example: `alice` variable was used instead of the (supposedly correct) `anita`.

FIX: typo in variable name in README

---

samples/simple-ts/README.md
samples/simple-ts/docker-compose-yugabytedb.yml

This PR adds a docker compose in `simple-ts` to start YugabyteDB instead of PostgreSQL.
YugabyteDB is an Open Source PostgreSQL-compatible Distributed SQL. It can scale horizontally by simply adding new nodes.
Example, here is a 6 nodes YugabyteDB cluster with Replication Factor 3 (resilient to one node failure):
```
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=0
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=1
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=2
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=3
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=4
docker-compose -f docker-compose-yugabytedb.yml up -d --scale dist=5
```
The application connects to any node with the same driver as …

YugabyteDB as a distributed alternative to PostgreSQL

---

src/package-lock.json
src/package.json
src/packages/dumbo/package.json
src/packages/dumbo/src/connections/client.ts
src/packages/dumbo/src/connections/connectionString.ts
src/packages/dumbo/src/connections/index.ts
src/packages/dumbo/src/connections/pool.ts
src/packages/pongo/package.json
src/packages/pongo/src/e2e/compatibilityTest.e2e.spec.ts
src/packages/pongo/src/main/client.ts
src/packages/pongo/src/main/dbClient.ts
src/packages/pongo/src/main/index.ts
src/packages/pongo/src/main/pongoClient.ts
src/packages/pongo/src/postgres/client.ts
src/packages/pongo/src/postgres/postgresCollection.ts

That will enable running transactions and sharing connections with Emmett projections.
Fixed connection pool management to correctly handle database names. This is needed as PostgreSQL connection pool is resolved per database. Thanks to that, `pongoClient.close` can close connection pools without needing to call `endAllPools`. `endAllPoolls` still applies if you want to brute force close all active connection pools.
PongoClient will track opened dbClients and close them all.

Added option to inject PoolClient to PongoClient as the first step for transaction handling

---

src/packages/pongo/src/main/typing/operations.ts
src/packages/pongo/src/mongo/mongoCollection.ts
src/packages/pongo/src/postgres/postgresCollection.ts

Used it also for `count` and `estimatedDocumentCount`.

Exposed countDocuments method

---

README.md
src/docs/getting-started.md
src/packages/pongo/src/postgres/postgresCollection.ts

Changed _id type to Text. In PostgreSQL, this should be almost equally the same indexable. Of course, it'll take a bit more storage, but let's live with that for now.
We can, in the future, allow, as Marten does, to use different definitions of collection tables.
Changing from `uuid` to text will allow more sophisticated key strategies.
Most importantly, it'll reuse the stream ID as a document ID for Emmett projections.
Besides that, I added columns for future concepts:
- `_version` - for optimistic concurrency handling,
- `_partition` - for built-in PostgreSQL partitioning,
- `_created`, `_modified` - for timestamp metadata,
- `metadata` - for technical additional data,
- `_archived` - for soft deletion and also partitioning

Changed _id type to TEXT

---

src/packages/pongo/src/main/typing/operations.ts
src/packages/pongo/src/mongo/mongoCollection.ts
src/packages/pongo/src/postgres/postgresCollection.ts

That closes all the basic methods support. Of course, they're not yet fully aligned with Mongo, but we'll get there.

Added findOneAndDelete, findOneAndReplace, findOneAndUpdate methods

---

src/package-lock.json
src/package.json
src/packages/pongo/package.json
src/packages/pongo/src/main/pongoClient.ts
src/packages/pongo/src/mongo/mongoClient.ts
src/packages/pongo/src/postgres/client.ts

It seems that it was exposed in postgresClient but not in the final pool client.

Exposed option to inject pg.PoolClient

---

src/package-lock.json
src/packages/dumbo/package.json
src/packages/dumbo/src/core/connections/connection.ts
src/packages/dumbo/src/core/connections/pool.ts
src/packages/dumbo/src/core/connections/transaction.ts
src/packages/dumbo/src/core/execute/execute.ts
src/packages/dumbo/src/index.ts
src/packages/dumbo/src/postgres/index.ts
src/packages/dumbo/src/postgres/pg/connections/connection.int.spec.ts
src/packages/dumbo/src/postgres/pg/connections/connection.ts
src/packages/dumbo/src/postgres/pg/connections/pool.ts
src/packages/dumbo/src/postgres/pg/connections/transaction.ts
src/packages/pongo/package.json
src/packages/pongo/src/core/pongoClient.connections.int.spec.ts
src/packages/pongo/src/core/pongoClient.ts
src/packages/pongo/src/postgres/dbClient.ts

Fixes #53
Now, it should be easier to implement new ones.
Added also useful helpers that should make the Dumbo usable even as a standalone too. You can do the following:
```ts
import { dumbo, rawSql } from '@event-driven-io/dumbo';
const pool = dumbo({ connectionString });
const result = await pool.execute.query<User>(rawSql('SELECT * from users'));
````
or with transactions:
````ts
import { dumbo, sql } from '@event-driven-io/dumbo';
const userId = 32;
const userName = "test@test.com";
const pool = dumbo({ connectionString });
await pool.withTransaction(async ({ execute }) => {
await execute.command(sql('INSERT INTO users VALUES(%s, %L)', userId, userName));
await execute.command(sql('INSERT INTO user_roles VALUES(%s, %L)', userId, 'admin') );
})
````
You can now also share the …

Cleaned up connection setup by wrapping it with factory method

---

src/package-lock.json
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/typing/operations.ts
src/packages/pongo/src/e2e/postgres.e2e.spec.ts
src/packages/pongo/src/postgres/sqlBuilder/index.ts
src/packages/pongo/src/shim/index.ts
src/packages/pongo/src/shim/mongoCollection.ts
src/packages/pongo/src/shim/typing.ts

Adjusted also typing to be more aligned with MongoDB API (relates to #41).

Fixed findOne, countDocuments and other queries that don't have filter

---

src/package-lock.json
src/package.json
src/packages/dumbo/package.json
src/packages/dumbo/src/benchmarks/index.ts

To run them, you either need to define `BENCHMARK_POSTGRESQL_CONNECTION_STRING` environment variable, or setup it through `.env` file in `src/packages/dumbo/src` folder. If not provided, it'll use the default docker config, so: `postgresql://postgres@localhost:5432/postgres`.
You can also set `BENCHMARK_CONNECTION_POOLED` to `true` or `false` to decide if you're running pooled or non-pooled connection.
You can run it through cmd line going to `src` folder:
```shell
$ npm run benchmark --workspace=@event-driven-io/dumbo
````
Currently when I run them against the basic free tier NeonDB in FRA region (I'm in Poland) I got:
- For pooled connection
```
INSERTING records in transaction x 9.60 ops/sec ±0.59% (49 runs sampled)
READING records x 28.74 ops/sec ±0.88% (68 runs sampled)
Benchmark: …
```

Added basic benchmarks for writes and reads

---

src/packages/dumbo/src/postgres/migrations/index.ts
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/pongoClient.connections.int.spec.ts
src/packages/pongo/src/core/pongoClient.ts
src/packages/pongo/src/core/pongoDb.ts
src/packages/pongo/src/postgres/dbClient.ts

Besides that:
- nested connection options to allow passing easier other parameters, e.g. schema configuration.

Added possibility to disable generating Pongo schema upfront

---

src/packages/dumbo/src/core/schema/index.ts
src/packages/dumbo/src/core/schema/migrations.ts
src/packages/dumbo/src/core/schema/schemaComponent.ts

Added also schema component group for grouping multiple components. For instance Emmett PostgreSQL event store will be built from event store component and read model projections.

Added schema component that will be used to contain migrations for collections, etc.

---

src/package-lock.json
src/package.json
src/packages/pongo/package.json
src/packages/pongo/src/commandLine/configFile.ts

It's not super critical, but I used `,` instead of `;` in the type template in the sample config file generation. This PR changes that.

Fixed sample CLI config template

---

samples/simple-ts/src/shim.ts
samples/simple-ts/src/typedClient.ts
src/package-lock.json
src/package.json
src/packages/dumbo/src/postgres/pg/execute/execute.ts
src/packages/pongo/package.json
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/typing/operations.ts
src/packages/pongo/src/mongo/mongoCollection.ts

- Fixed custom sql operations typing in PongoCollection type
- Returned WithIdAndVersion from find methods

Fixed custom sql operations typing in PongoCollection typing and Find methods results

---

README.md
samples/simple-ts/src/index.ts
samples/simple-ts/src/typedClient.ts
src/docs/getting-started.md
src/package-lock.json
src/package.json
src/packages/dumbo/package.json
src/packages/pongo/package.json
src/packages/pongo/src/commandLine/shell.ts
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/typing/operations.ts
src/packages/pongo/src/e2e/compatibilityTest.e2e.spec.ts
src/packages/pongo/src/e2e/postgres.e2e.spec.ts
src/packages/pongo/src/e2e/postgres.optimistic-concurrency.spec.ts

I also added the ObjectId helper method to generate it with a Mongo-like style.

Used UUID v7 as sequential random id generator

---

src/packages/pongo/src/commandLine/shell.ts

It's still possible to enable it by calling printResultsAsTable() in shell.

Made printing results in shell as table optional and disabled by default

---

src/package-lock.json
src/package.json
src/packages/pongo/package.json
src/packages/pongo/src/commandLine/shell.ts
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/e2e/postgres.e2e.spec.ts

This fixes the regression introduced by #99
@jameswoodley FYI

Handle method passes again null instead of empty object when doucument doesn't exists

---

src/package-lock.json
src/package.json
src/packages/dumbo/package.json
src/packages/dumbo/src/core/tracing/printing/color.ts
src/packages/dumbo/src/core/tracing/printing/index.ts
src/packages/dumbo/src/core/tracing/printing/pretty.ts
src/packages/dumbo/src/core/tracing/printing/pretty.unit.spec.ts
src/packages/dumbo/tsup.config.ts
src/packages/pongo/package.json
src/packages/pongo/src/commandLine/shell.ts
src/packages/pongo/tsup.config.ts
src/tsup.config.ts

It seems that Chalk from v5 is ESModules-only

Replaced chalk by ansis to keep Pongo compatible with CommonJS

---

LICENSE

We're making an important change to our project's license, moving from MIT to Apache 2.0. I wanted to take a moment to explain this change and why we believe it's beneficial for our community.
After careful consideration, we've decided to adopt the Apache 2.0 license for several good reasons:
Apache 2.0 provides more detailed guidelines around contributions, modifications, and usage rights. This clarity benefits everyone by reducing potential misunderstandings as our project grows.
Many established open-source projects use Apache 2.0, particularly in enterprise settings. Adopting this license aligns us with common practices in the broader open-source community.
The Apache 2.0 license includes an express patent grant that MIT doesn't offer. This provides everyone with clearer protection …

Set License to Apache 2.0

---

src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/typing/operations.ts
src/packages/pongo/src/e2e/compatibilityTest.e2e.spec.ts
src/packages/pongo/src/mongo/mongoCollection.ts
src/packages/pongo/src/storage/postgresql/sqlBuilder/index.ts
src/packages/pongo/src/storage/postgresql/sqlBuilder/sqlBuilder.unit.spec.ts

This PR introduces support for limit and skip options in the find() query method. These options allow more flexible querying by enabling pagination and result size control.

Implement 'limit' and 'skip' options in find()

---

src/packages/dumbo/src/core/schema/migrations.ts
src/packages/dumbo/src/core/schema/schemaComponent.ts
src/packages/dumbo/src/storage/postgresql/core/schema/migrations.ts
src/packages/dumbo/src/storage/sqlite/core/schema/migrations.ts
src/packages/pongo/src/commandLine/migrate.ts
src/packages/pongo/src/core/collection/pongoCollection.ts
src/packages/pongo/src/core/pongoDb.ts

After recent changes in https://github.com/event-driven-io/Pongo/pull/118 we don't need to pass the connector anymore, as it'll be resolved when running migrations based on the passed dumbo instance.

Simplified schema component migrations to be an array instead of function with connector type

---

src/packages/dumbo/src/core/schema/migrations.ts
src/packages/dumbo/src/core/schema/schemaComponent.ts
src/packages/pongo/src/commandLine/migrate.ts
src/packages/pongo/src/core/pongoDb.ts

Thanks to that, we can add abstractions on top of the schema component (like Table, Index, etc.) that will be defined in a database-agnostic way and have the final SQL resolved upon running.
That opens the possibility to have a pluggable way to define default migration, Pongo collection, etc., without a big hassle.

Enabled schema component migrations to be resolved lazily based on the database type
